image: atlassian/default-image:3
pipelines:
  branches:
    master:
      - step:
          name: Build and push images
          script:
            - IMAGE_NAME="esimplus-blog"
            - VERSION="0.1.${BITBUCKET_BUILD_NUMBER}"
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - docker build . -t "${IMAGE_NAME}-${VERSION}"
            - docker push "appvillisdocker/landings:${IMAGE_NAME}-${VERSION}"