image: atlassian/default-image:3
pipelines:
  custom:
    build-and-deploy:
      - step:
          name: Build and push image
          script:
            - IMAGE_NAME=esimplus-blog
            - VERSION=0.1.${BITBUCKET_BUILD_NUMBER}
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - docker build . -t "landings:${IMAGE_NAME}-${VERSION}"
            - docker tag "landings:${IMAGE_NAME}-${VERSION}" "appvillisdocker/landings:${IMAGE_NAME}-${VERSION}"
            - docker push "appvillisdocker/landings:${IMAGE_NAME}-${VERSION}"
          services:
            - docker
      - step:
          name: Deploy dev
          script:
            - IMAGE_NAME=esimplus-blog
            - VERSION=0.1.${BITBUCKET_BUILD_NUMBER}
            - sed -i 's/IMAGE_NAME_VALUE/'"$IMAGE_NAME"'/g' ./deploy-dev.sh
            - sed -i 's/VERSION_VALUE/'"$VERSION"'/g' ./deploy-dev.sh
            - cat ./deploy-dev.sh
            - cat ./deploy-dev.sh | ssh ${DEPLOY_USER}@${DEPLOY_HOST}
      - step:
          name: Deploy prod
          trigger: manual
          script:
            - IMAGE_NAME=esimplus-blog
            - VERSION=0.1.${BITBUCKET_BUILD_NUMBER}
            - sed -i 's/IMAGE_NAME_VALUE/'"$IMAGE_NAME"'/g' ./deploy-prod.sh
            - sed -i 's/VERSION_VALUE/'"$VERSION"'/g' ./deploy-prod.sh
            - cat ./deploy-prod.sh
            - cat ./deploy-prod.sh | ssh ${DEPLOY_USER}@${DEPLOY_HOST}      
definitions:
  services:
    docker:
      memory: 3072 